### ISSUE TITLE
Mac OS X build error (template/types)

### ISSUE THREAD

**Issue by herve-gross** [LLNL/Adiak#3]
Hi there,

I have been able to build Adiak on Mac OS X fine, but when I try to use it as third party library in another code, I am getting a template type conversion error. Here is the console output for the build:

`In file included from /Users/j0529096/Documents/code/thirdPartyLibs/for_caliper_install/adiak/include/adiak.hpp:52:
/Users/j0529096/Documents/code/thirdPartyLibs/for_caliper_install/adiak/include/adiak_internal.hpp:153:40: error: cannot
      initialize a parameter of type 'void *' with an lvalue of type 'long long'
            element_type<T>::set(*val, obj);
                                       ^~~
/Users/j0529096/Documents/code/thirdPartyLibs/for_caliper_install/adiak/include/adiak.hpp:129:48: note: in instantiation of
      member function 'adiak::internal::parse<long long>::make_value' requested here
      bool result = adiak::internal::parse<T>::make_value(value, avalue, datatype);
                                               ^
/Users/j0529096/Documents/code/GEOSX/src/coreComponents/managers/initialization.hpp:155:10: note: in instantiation of
      function template specialization 'adiak::value<long long>' requested here
  adiak::value( name + " sum", total );
         ^
/Users/j0529096/Documents/code/GEOSX/src/coreComponents/managers/initialization.cpp:184:3: note: in instantiation of
      function template specialization 'geosx::pushStatsIntoAdiak<long long>' requested here
  pushStatsIntoAdiak( "numThreads", numThreads );
  ^
/Users/j0529096/Documents/code/thirdPartyLibs/for_caliper_install/adiak/include/adiak_internal.hpp:37:50: note: passing
      argument to parameter 'p' here
         static void set(adiak_value_t &v, void *p) { v.v_ptr = p; }
                                                 ^
1 error generated.`

This is a Release build, with AppleClang 11.0.3.11030032 and Adiak-0.2.0.

Thanks for your help on this,

Herve

**Comment by daboehme** [comment]
Looks like we don't have specialization for `long long` and the default C++ behavior is dumb. As a workaround, can you try converting the offending values to something else like `int` in your initialization.cpp, e.g. `pushStatsIntoAdiak( "numThreads", static_cast<int>(numThreads) );`?

**Comment by herve-gross** [comment]
Ha! Thanks, it compiles fine now. Good to know.

**Comment by corbett5** [comment]
@daboehme could you add a specialization for `long long`? We use `std::int64_t` for indexing across MPI ranks, of course we could just convert this into a `long` when pushing into Adiak but that doesn't seem like a permanent solution.

**Comment by daboehme** [comment]
Yes, I think adding a specialization for `long long` would be best. I can add that.

**Comment by corbett5** [comment]
Awesome, thanks!

**Comment by daboehme** [comment]
Ok, this is going to be a bit more involved than I initially though. Adiak currently doesn't have a 64bit integer type at all, so we need to add that. This will be an API change, so we'll also have to update Adiak-based tools etc. All doable, but it won't be a quick fix unfortunately.
